### ISSUE TITLE
Github: Dependabot on the Loose

### ISSUE THREAD

**Issue by CodeforEvolution** [haiku/website-inc#11]
We seem to be at 7 pull requests now from Dependabot...are we able to merge any of these updates in? Is the haiku-inc.org website able to automatically rebuild and auto-deploy itself like the main haiku-os.org website?

**Comment by nielx** [comment]
While admirable, dependabot is not very helpful, as the modules may have security issues, but they are not exposed to the outside world...

I see a link to disable PRs from dependabot, so if others would like me to do so I can click that. 

Having said that, there may be value in keeping the dependencies up to date?

**Comment by kallisti5** [comment]
Disabled depend-a-bot and PR's closed.  It's a static site, not really too concerned about nodejs vulnerabilities
